//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APPFLOWDM
    {
        public int ID { get; set; }
        public string DIVISION { get; set; }
        public string PAGE { get; set; }
        public string USER { get; set; }
        public Nullable<int> LEVEL { get; set; }
        public Nullable<decimal> LIMIT { get; set; }
        public string REMARK { get; set; }
        public string EMAIL { get; set; }
        public string FLAG { get; set; }
    }
}
