//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRVLFOREXPENDITURED
    {
        public int RDID { get; set; }
        public string REQNO { get; set; }
        public Nullable<int> COSTCODE { get; set; }
        public string ITEMID { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> UNITRATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public string SUPLR { get; set; }
        public string UOMSR { get; set; }
        public string DESCSR { get; set; }
        public bool CANSTATUS { get; set; }
        public decimal DISC { get; set; }
        public bool DPERC { get; set; }
        public Nullable<decimal> ADVURATE { get; set; }
        public Nullable<decimal> ADVAT { get; set; }
        public Nullable<decimal> NETURATE { get; set; }
    }
}
