//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class APRVLFOREXPENDITURE
    {
        public int RID { get; set; }
        public string REQNO { get; set; }
        public Nullable<System.DateTime> RTDATE { get; set; }
        public string REFERENCE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<System.DateTime> RQDATE { get; set; }
        public string REQUESTERID { get; set; }
        public string FLOWCODE { get; set; }
        public string PAYTID { get; set; }
        public string SHIPMENTID { get; set; }
        public string CONTACTPRSN { get; set; }
        public string CONTACTNO { get; set; }
        public string REMARK { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public string STATUS { get; set; }
        public string REQTYPE { get; set; }
        public Nullable<bool> CANASTATUS { get; set; }
        public bool HPERC { get; set; }
        public decimal HDISC { get; set; }
        public string WONO { get; set; }
        public bool VPERC { get; set; }
        public decimal VVALUE { get; set; }
        public string EMAIL { get; set; }
        public string MATCLEAR { get; set; }
        public string SHIPMENTCLEAR { get; set; }
        public string SHIPMENTCLEARNOTE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> FREIGHT { get; set; }
        public Nullable<decimal> PACKING { get; set; }
        public Nullable<decimal> MICSCHARGE { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> NETTOTAL { get; set; }
    }
}
