//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CCMAST
    {
        public string CODE { get; set; }
        public string NAME { get; set; }
        public string COMPANY { get; set; }
        public string BRANCH { get; set; }
        public string DIV { get; set; }
        public string TYPE { get; set; }
        public bool ACTIVE { get; set; }
    }
}
