//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        public string CUCCD { get; set; }
        public string CUCNA { get; set; }
        public string CUCUR_CD { get; set; }
        public string CUDEC_NAME { get; set; }
        public int Id { get; set; }
        public string ACUNA { get; set; }
        public Nullable<bool> Cur { get; set; }
    }
}
