//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILESMANAGEMENT
    {
        public int ID { get; set; }
        public string DOCNO { get; set; }
        public string FNAME { get; set; }
        public string FPATH { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public Nullable<bool> ACTIVE { get; set; }
        public byte[] FILELOG { get; set; }
        public string FILETYPE { get; set; }
        public Nullable<long> FILESIZE { get; set; }
        public Nullable<System.DateTime> EXPIRY { get; set; }
    }
}
