//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INPAYTERM
    {
        public string PAY_CD { get; set; }
        public string PAY_DESC { get; set; }
        public Nullable<int> PAY_DAYS { get; set; }
        public string PAY_TYPE { get; set; }
    }
}
