//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASEORDER
    {
        public int ID { get; set; }
        public string PONO { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
        public string SHIPTERM { get; set; }
        public string DELMODE { get; set; }
        public string REQNO { get; set; }
        public string SUPNAME { get; set; }
        public string REMARK { get; set; }
        public Nullable<bool> POSTATUS { get; set; }
        public Nullable<System.DateTime> DELDATE { get; set; }
        public Nullable<bool> CANPSTATUS { get; set; }
        public string SUPMAIL { get; set; }
        public string SUPCPRSN { get; set; }
        public Nullable<decimal> POVALUE { get; set; }
        public string SHIPTO { get; set; }
        public string PYTERM { get; set; }
        public Nullable<bool> REVISE { get; set; }
        public string FLAG { get; set; }
        public decimal PDISC { get; set; }
        public bool PPERC { get; set; }
        public string WONO { get; set; }
        public string COMENT { get; set; }
        public bool POVAT { get; set; }
        public decimal POVATVAL { get; set; }
        public Nullable<decimal> GTOTAL { get; set; }
        public Nullable<decimal> DTOTAL { get; set; }
        public Nullable<decimal> NTOTAL { get; set; }
        public Nullable<decimal> FREIGHT { get; set; }
        public Nullable<decimal> PACKING { get; set; }
        public Nullable<decimal> MICSCHARGE { get; set; }
        public Nullable<decimal> SUBTOTAL { get; set; }
        public Nullable<decimal> EXCH { get; set; }
        public string CUR { get; set; }
        public Nullable<decimal> STOTAL { get; set; }
    }
}
