//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASEORDERDCANCEL
    {
        public int ID { get; set; }
        public string PONO { get; set; }
        public string C_C { get; set; }
        public string ITEM { get; set; }
        public string UOM { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<decimal> CQTY { get; set; }
        public Nullable<decimal> RATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> ETA { get; set; }
        public string DESCR { get; set; }
        public Nullable<decimal> DPDISC { get; set; }
        public Nullable<bool> DPPERC { get; set; }
        public Nullable<int> PLNO { get; set; }
    }
}
