//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rtUser
    {
        public int ID { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserPwd { get; set; }
        public Nullable<bool> UserActive { get; set; }
        public string UserMail { get; set; }
        public string UserEmpID { get; set; }
        public byte[] UserSign { get; set; }
        public Nullable<decimal> Mobile { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public string LocId { get; set; }
        public Nullable<System.DateTime> ValidFr { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string Path { get; set; }
    }
}
