//------------------------------------------------------------------------------
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupHeader
    {
        public int Id { get; set; }
        public string SId { get; set; }
        public string Cname { get; set; }
        public Nullable<System.DateTime> SubDate { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> Country { get; set; }
        public Nullable<decimal> Phone { get; set; }
        public Nullable<decimal> Mobile { get; set; }
        public Nullable<decimal> Fax { get; set; }
        public string Web { get; set; }
        public string Email { get; set; }
        public string ContactBy { get; set; }
        public string Position { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> TDate { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
        public Nullable<System.DateTime> REDate { get; set; }
        public Nullable<int> SupType { get; set; }
        public string Remark { get; set; }
        public string Cat1 { get; set; }
        public string Cat2 { get; set; }
        public string Cat3 { get; set; }
        public string Cat4 { get; set; }
        public string Cat5 { get; set; }
        public string Cat6 { get; set; }
        public string Email2 { get; set; }
        public string LicenseNo { get; set; }
        public string PlaceLns { get; set; }
        public Nullable<bool> Local { get; set; }
        public string Activity { get; set; }
        public string PCode { get; set; }
        public string POBox { get; set; }
        public string Comp1 { get; set; }
        public string Comp2 { get; set; }
        public string Comp3 { get; set; }
        public string Comp4 { get; set; }
        public string Loc1 { get; set; }
        public string Loc2 { get; set; }
        public string Loc3 { get; set; }
        public string Loc4 { get; set; }
        public string OtherOffices { get; set; }
        public string Flag { get; set; }
        public string PAY_TERM { get; set; }
        public string QName { get; set; }
        public string QEMail { get; set; }
        public string QMobile { get; set; }
        public Nullable<bool> QMSIMP { get; set; }
        public Nullable<bool> QMSCERT { get; set; }
        public Nullable<bool> QMSSTD1 { get; set; }
        public Nullable<bool> HSESIMP { get; set; }
        public Nullable<bool> HSECERT { get; set; }
        public Nullable<bool> HSESTD1 { get; set; }
        public Nullable<bool> HSESTD2 { get; set; }
        public Nullable<bool> HSESTD3 { get; set; }
        public Nullable<bool> QMSSTD2 { get; set; }
        public Nullable<bool> QMSSTD3 { get; set; }
        public string TRN { get; set; }
    }
}
