//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAndPg
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string PName { get; set; }
        public string Desc { get; set; }
        public string Group { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Tab { get; set; }
    }
}
