//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPageAvailable
    {
        public int Id { get; set; }
        public string PgCode { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Delete { get; set; }
        public Nullable<bool> Submit { get; set; }
        public Nullable<bool> Approval { get; set; }
        public Nullable<bool> Activity { get; set; }
        public Nullable<bool> AppHist { get; set; }
        public Nullable<bool> View { get; set; }
    }
}
