//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Core.DbHelper.App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInbox
    {
        public int Id { get; set; }
        public string TTD_CD { get; set; }
        public string PageId { get; set; }
        public string TTD_Level { get; set; }
        public string UserId { get; set; }
        public string Work { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string TransId { get; set; }
        public string Adres { get; set; }
        public Nullable<bool> Flag { get; set; }
    }
}
